### ISSUE TITLE
How to configure user?

### ISSUE THREAD

**Issue by GhostYiL** [a13labs/m3uproxy#1]
So the docs mention on using **`./m3uproxy users add -c config.json user pass.`**
But while doing so im receiving **`unexpected end of JSON input`** error. 

_My config:_
```{
    "port": 8080,
    "epg": "https://m3upt.com/epg",
    "m3u":"http://supercoollisthere.com/bigcars.m3u",
    "playlist": "/path/to/playlist.json",
    "no_service_image": "/path/to/image.jpg",
    "default_timeout": 3,
    "num_workers": 10,
    "scan_time": 600,
    "security": {
        "geoip": {
            "database": "/path/to/GeoLite2-Country.mmdb",
            "whitelist": [],
            "internal_networks": [
                "127.0.0.0/8"
            ]
        },
        "allowed_cors_domains": [
            "*"
        ]
    },
    "auth": {
        "provider": "file",
        "secret_key": "secret",
        "settings": {
            "file_path": "/path/to/auth.json"
        }
    }
}
```

How are you supposed to configure auth.json?

**Comment by alexyz79** [comment]
Indeed the command should work, it is also being used in Dockerfile (https://github.com/a13labs/m3uproxy/blob/main/scripts/entrypoint.sh#L31), I will take a look ASAP.

**Comment by alexyz79** [comment]
After checking, the command should work, either the file is created or either the file is updated. If for some reason the file already exists it must be a valid json file with the following body:
```json
{
  "users":[]
}
```
